name: "Build Images"

on:
  push:
    branches:
      - "main"
      - "develop"
  pull_request:
    types: [opened, edited, reopened, synchronize]
    paths:
      - "modules/**"
      - ".github/workflows/build.yml"
      - ".github/workflows/build-image.yml"
      - "config.yml"
  workflow_dispatch:

concurrency:
  group: ci-build-${{ github.ref }}-1
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/build-image.yml
    with:
      upload_to_release: false
